[package]
name = "futures_compat"
version = "0.1.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

[dependencies]
snafu = { path = "../..", features = ["futures-01"] }
futures = "0.1.27"
